{{- $ca := genCA "rabbitmq-topology-ca" 3650 }}
{{- $servingCert := genSignedCert "webhook-service.rabbitmq-system.svc" nil (list "webhook-service.rabbitmq-system.svc" "webhook-service.rabbitmq-system.svc.cluster.local") 365 $ca }}
{{- if not .Values.useCertManager }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: rabbitmq-system
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $servingCert.Cert | b64enc | quote }}
  tls.key: {{ $servingCert.Key | b64enc | quote }}
---
{{- end }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  {{- if .Values.useCertManager }}
  annotations:
    cert-manager.io/inject-ca-from: rabbitmq-system/serving-cert
  {{- end }}
  name: topology.rabbitmq.com
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-binding
  failurePolicy: Fail
  name: vbinding.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-exchange
  failurePolicy: Fail
  name: vexchange.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - exchanges
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-federation
  failurePolicy: Fail
  name: vfederation.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - federations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-permission
  failurePolicy: Fail
  name: vpermission.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - permissions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-policy
  failurePolicy: Fail
  name: vpolicy.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-queue
  failurePolicy: Fail
  name: vqueue.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - queues
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-schemareplication
  failurePolicy: Fail
  name: vschemareplication.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - schemareplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-shovel
  failurePolicy: Fail
  name: vshovel.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shovels
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-topicpermission
  failurePolicy: Fail
  name: vtopicpermission.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - topicpermissions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-user
  failurePolicy: Fail
  name: vuser.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1beta1-vhost
  failurePolicy: Fail
  name: vvhost.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vhosts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.useCertManager }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    service:
      name: webhook-service
      namespace: rabbitmq-system
      path: /validate-rabbitmq-com-v1alpha1-superstream
  failurePolicy: Fail
  name: vsuperstream.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - superstreams
  sideEffects: None
