apiVersion: v2
name: rabbitmq-cluster-operator
description: Helm chart for RabbitMQ Cluster Operator wrapping upstream manifests
type: application
version: 2.23.0
appVersion: "2.23.0"
annotations:
  messaging-topology-operator-version: "1.12.1"
