clusterOperator:
  image:
    registry: docker.io
    repository: bitnamilegacy/rabbitmq-cluster-operator
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
msgTopologyOperator:
  image:
    registry: docker.io
    repository: bitnamilegacy/rmq-messaging-topology-operator
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
rabbitmqImage:
  registry: docker.io
  repository: bitnamilegacy/rabbitmq
  version: 3.11.26-debian-11-r0
credentialUpdaterImage:
  registry: docker.io
  repository: bitnamilegacy/rmq-default-credential-updater
