name: Publish Helm Chart
on:
  push:
    tags:
      - "v*"
permissions:
  contents: read
  packages: write

env:
  HELM_VERSION: vbacluc-test-user
  HELM_IMAGE: ghcr.io/appuio/helm-v4

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      HELM_COMMAND: "docker run --rm -it --user $UID --volume \"$PWD\":/app --workdir /app --volume ~/.config/helm/registry/:/helm/registry --env HELM_REGISTRY_CONFIG=/helm/registry/config.json ${{ github.env.HELM_IMAGE }}:${{ github.env.HELM_VERSION }}"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: setup helm
        run: |
          mkdir -p ~/.config/helm/registry/
          echo "{}" > ~/.config/helm/registry/config.json

      - name: Package Helm chart
        run: |
         $HELM_COMMAND package .

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            $HELM_COMMAND registry login ghcr.io \
              --username "${{ github.actor }}" \
              --password-stdin

      - name: Push Helm chart
        run: |
          $HELM_COMMAND push ./*.tgz \
            oci://ghcr.io/${{ github.repository }}
