name: Publish Helm Chart
on:
  push:
    tags:
      - "v*"
permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/appuio/helm-v4:vbacluc-test-user
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Package Helm chart
        run: |
          helm package .

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            helm registry login ghcr.io \
              --username "${{ github.actor }}" \
              --password-stdin

      - name: Push Helm chart
        run: |
          helm push ./*.tgz \
            oci://ghcr.io/${{ github.repository }}
